- name: Install the Links
  homebrew:
    name: links
    state: present

- name: Install the Firefox
  homebrew_cask:
    name: firefox
    state: present

- name: Install the Chrome
  homebrew_cask:
    name: google-chrome
    state: present
