- name: Install the CLI for Web develop
  homebrew:
    name:
      - mkcert
      - nss
    state: present

- name: Install the CLI for AWS
  homebrew:
    name:
      - awscli
      - czmq
      - pkg-config
      - zmqpp
    state: present

- name: Install the Powershell Core
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - dotnet-sdk
    - powershell

- name: Install the Develop environment for mobile app
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - adoptopenjdk
    - android-studio
    - unity-hub
    - visual-studio
