# App Store: LINE, Slack

- name: Install the Discord
  homebrew_cask:
    name: discord
    state: present

- name: Install the Facebook messenger
  homebrew_cask:
    name: messenger
    state: present

- name: Install the Keybase
  homebrew_cask:
    name: keybase
    state: present

- name: Install the Skype
  homebrew_cask:
    name: skype
    state: present
