- name: Install the remote tools
  homebrew:
    name:
      - git
      - git-lfs
      - gist
      - subversion
      - telnet
      - wget
    state: present

- name: Initialize the Git LFS
  shell: git lfs install
  changed_when: false

- name: Install the remote apps
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - parallels-access
    - vysor

- name: Install the Cloud storage tools
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - adobe-creative-cloud
    - dropbox
    - omnipresence
