- name: Install the auth utils
  homebrew:
    name:
      - gnupg
      - pinentry-mac
    state: present

- name: Install the utils for devices
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - homebrew/cask-drivers/drobo-dashboard
    - amorphousdiskmark
    - audio-hijack
    - haptickey
    - loopback
    - nosleep
    - sidequest

- name: Install the miscs utils
  homebrew:
    name:
      - jq
      - mackup
      - p7zip
      - pandoc
      - rename
      - rsync
      - unrar
      - watch
    state: present
