- name: Unlock sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: '{{ ansible_env.USER }} ALL=\(ALL\) NOPASSWD: ALL'
    line: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  become: yes

- name: Disable the Gatekeeper
  shell: spctl --master-disable
  become: true
  changed_when: false

- import_tasks: __shell.yml
- import_tasks: _anyenv.yml
- import_tasks: _anyenv_node.yml
  vars:
    node_ver: 10
- import_tasks: _anyenv_node.yml
  vars:
    node_ver: 12
- import_tasks: _anyenv_node.yml
  vars:
    node_ver: 13
- import_tasks: _anyenv_npm.yml
- import_tasks: _desktop.yml
- import_tasks: _dev.yml
- import_tasks: _editors.yml
- import_tasks: _remote.yml
- import_tasks: _utils.yml

- name: Whether the environment on VM
  stat:
    path: /vagrant
  register: vagrant

- import_tasks: _virts.yml
  when: not vagrant.stat.exists

- name: Upgrade brew.
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Restore the Gatekeeper
  shell: spctl --master-enable
  become: true
  changed_when: false

- name: Lock sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: '{{ ansible_env.USER }} ALL=\(ALL\) NOPASSWD: ALL'
    line: ""
    validate: visudo -cf %s
  become: yes

- meta: flush_handlers
