- name: Reboot
  import_tasks: ../_common/handlers/reboot.yml

- name: Reload Dock
  shell: killall Dock
  ignore_errors: true

- name: Reload Finder
  shell: killall Finder
  ignore_errors: true

- name: Reload sshd
  import_tasks: _sshd.yml
